spring:
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file:c:/tmp/customer
    username: sa
    password:
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: validate

