spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-163-236-33.compute-1.amazonaws.com:5432/d44vhgpki3hoh4?sslmode=require&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: hgqtktjpmesals
    password: 48eb4dacff9b70e3faf890c08b242a3262fbb238bbc562a38540907a16eb6756
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

security:
  basic:
    enabled: false
---
spring:
  profiles: heroku
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate

