spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/tmp/customer
    username: sa
    password:
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: none
    database: h2
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

security:
  basic:
    enabled: false
---
spring:
  profiles: heroku
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
flyway:
  validate-on-migrate: false

